version: '3'

tasks:

  default:
    desc: Run all tasks
    cmds:
      - task lint
      - task type-check
      - task test

  lint:
    desc: Check code with ruff (linting and formatting)
    cmds:
      - ruff check ./src
      - ruff format --check ./src

  lint-fix:
    desc: Fix code issues with ruff (linting and formatting)
    cmds:
      - ruff check --fix ./src
      - ruff format ./src

  test:
    desc: Run test with pytest
    cmds:
      - pytest ./test

  type-check:
    desc: Check types with mypy
    cmds:
      - mypy ./src